version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "3000"  # Exposing backend service to nginx (not directly to host)
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "80"  # Exposing frontend service to nginx (not directly to host)
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"    # Exposing HTTP port 80
      - "443:443"  # Exposing HTTPS port 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
